import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations object
const translations = {
  en: {
    'app.title': 'Afaq Al-ʿIlm',
    'app.tagline': 'Horizons of Knowledge',
    'nav.home': 'Home',
    'nav.curriculum': 'Curriculum',
    'nav.impact': 'Impact',

    'nav.contact': 'Contact',
    'nav.demo': 'Request Demo',
    'nav.login': 'Teacher Login',
    'hero.title.revolutionizing': 'Revolutionizing',
    'hero.title.steam': 'STEAM Education',
    'hero.subtitle': 'in Jordan',
    'hero.description': 'Empowering the next generation through hands-on STEAM learning with innovative curriculum kits, comprehensive teacher resources, and seamless bilingual support.',
    'steam.what.title': 'What is STEAM?',
    'steam.description': 'STEAM education integrates these five disciplines to create engaging, hands-on learning experiences that prepare students for real-world challenges and future careers.',
    'steam.science': 'Science',
    'steam.technology': 'Technology', 
    'steam.engineering': 'Engineering',
    'steam.arts': 'Arts',
    'steam.mathematics': 'Mathematics',
    'steam.explanation': 'Science, Technology, Engineering, Arts & Mathematics',
    'hero.cta.primary': 'Start Your Journey',
    'hero.cta.secondary': 'Sample Lessons',
    'hero.stats.lessons': 'Lessons',
    'hero.stats.schools': 'Schools',
    'hero.stats.students': 'Students',
    'curriculum.title': 'Kit Levels & Curriculum',
    'curriculum.subtitle': 'Progressive STEAM education designed for Jordan\'s educational standards, from foundational concepts to advanced engineering principles. Each level aligns with Ministry of Education curriculum requirements.',
    'curriculum.level1.title': 'Level 1 – Starter Kit (Grades 1–3)',
    'curriculum.level1.description': 'Focus: Creativity, motion, shapes, simple storytelling builds.',
    'curriculum.level2.title': 'Level 2 – Builder Kit (Grades 4–6)',
    'curriculum.level2.description': 'Focus: Simple machines, gears, pulleys, force, ratios.',
    'curriculum.level3.title': 'Level 3 – Engineer Kit (Grades 7–9)',
    'curriculum.level3.description': 'Focus: Real-world mechanisms, problem-solving, optimization.',
    'curriculum.structure.title': 'Curriculum Structure',
    'curriculum.structure.schedule': '24–30 weeks per year, 1 class/week',
    'curriculum.structure.cycles': '4 build cycles:',
    'curriculum.cycle1': 'Motion & Structure',
    'curriculum.cycle2': 'Gears & Power',
    'curriculum.cycle3': 'Real Mechanisms',
    'curriculum.cycle4': 'Innovation & Problem Solving',
    'curriculum.alignment': 'Each build linked to Jordan\'s science, mathematics, and computer science units',
    'curriculum.examples': 'Example builds: Pulley lift, Gearbox car, Dancing bot, Crank walker',
    'footer.description': 'Empowering the next generation of innovators through comprehensive STEM education that aligns with Jordan\'s educational standards.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.teacherPortal': 'Teacher Portal',
    'footer.sampleLessons': 'Sample Lessons',
    'footer.trainingMaterials': 'Training Materials',
    'footer.supportCenter': 'Support Center',
    'footer.copyright': '© 2025 {title}. All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.accessibility': 'Accessibility',
    'impact.title': 'Transforming Education',
    'impact.subtitle': 'Real results from schools across Jordan demonstrating the power of hands-on STEAM learning.',
    'testimonials.title': 'Voices of Success',
    'testimonials.subtitle': 'Hear from educators and students who have experienced the transformation firsthand.',

    'contact.title': 'Start Your Journey',
    'contact.subtitle': 'Ready to transform STEAM education at your school? Let\'s discuss how Afaq Al-ʿIlm can benefit your students.',
    'contact.form.school': 'School Name',
    'contact.form.contact': 'Contact Person',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.levels': 'Grade Levels Interested In',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Request',
    'dashboard.welcome': 'Welcome to Teacher Portal',
    'dashboard.curriculum': 'Browse Curriculum',
    'dashboard.resources': 'Teaching Resources',
    'dashboard.feedback': 'Submit Feedback',
    'stats.students.reached': 'Students Reached',
    'stats.trained.teachers': 'Trained Teachers', 
    'stats.lessons': 'Lessons',
    'stats.schools.reached': 'Schools Reached',
    'stats.satisfaction': 'Satisfaction Rate',
    'skills.problem.solving': 'Problem-Solving Skills',
    'skills.creative.thinking': 'Creative Thinking',
    'skills.collaboration': 'Collaboration',
    'skills.technical': 'Technical Skills',
    'curriculum.grades': 'Grades',
    'curriculum.lessons': 'lessons',
    'curriculum.viewDetails': 'View Details',
    'skills.outcomes.progress': 'Learning Outcomes Progress',
    'loading': 'Loading...',
    'vision.title': 'Our Vision',
    'vision.content': 'To revolutionize STEAM education in Jordan by making hands-on learning accessible to every student, fostering innovation, creativity, and critical thinking skills that prepare them for the challenges of tomorrow.',
    'mission.title': 'Our Mission',
    'mission.content': 'We provide comprehensive, bilingual STEAM education solutions through innovative curriculum kits, teacher training, and continuous support, partnering with schools to transform traditional learning into engaging, practical experiences that inspire the next generation of innovators and problem-solvers.',
    'lego.title': 'Learning with Building Blocks',
    'lego.subtitle': 'We use LEGO-style building pieces to make STEAM concepts tangible and fun. Students learn by building, experimenting, and discovering.',
    'lego.blocks.title': 'Colorful Building Blocks',
    'lego.blocks.description': 'Bright, interlocking pieces that help students understand structures, patterns, and engineering principles through hands-on construction.',
    'lego.mechanics.title': 'Moving Parts & Gears',
    'lego.mechanics.description': 'Wheels, gears, and mechanical elements that bring creations to life and demonstrate physics concepts in action.',
    'lego.smart.title': 'Smart Technology',
    'lego.smart.description': 'Simple motors and sensors that introduce programming and robotics in an approachable, LEGO-compatible way.',
    'lego.badge.creative': 'Creative Building',
    'lego.badge.learning': 'Learning by Doing',
    'interactive.learning.title': 'Learning with Interactive Building Blocks',
    'interactive.learning.subtitle': 'We use building pieces to make theoretical concepts tangible and enjoyable. Students learn through building, experimenting, and discovering.',
    'interactive.building.title': 'Building & Design',
    'interactive.building.description': 'Colorful building pieces help students understand structures and mechanisms',
    'interactive.testing.title': 'Experimenting & Testing',
    'interactive.testing.description': 'Students test their ideas and develop them through direct experimentation',
    'interactive.solutions.title': 'Creative Solutions',
    'interactive.solutions.description': 'Each student finds their own way to solve problems and challenges',
    'levels.title': 'Kit Levels & Curriculum',
    
    // Teacher Portal Translations
    'teacher.dashboard': 'Teacher Dashboard',
    'teacher.lessons': 'Lesson Plans',
    'teacher.announcements': 'Announcements',
    'teacher.resources': 'Resources',
    'teacher.welcome': 'Welcome',
    'teacher.logout': 'Logout',
    'teacher.login': 'Teacher Login',
    'teacher.totalLessons': 'Total Lessons',
    'teacher.completedLessons': 'Completed Lessons',
    'teacher.activeStudents': 'Active Students',
    'teacher.averageProgress': 'Average Progress',
    'teacher.startLesson': 'Start Lesson',
    'teacher.lessonPlan': 'Plan',
    'teacher.teacherGuide': 'Teacher Guide',
    'teacher.lessonMaterials': 'Lesson Materials',
    'teacher.curriculumPlanner': 'Curriculum Planner',
    'teacher.downloadPDF': 'Download PDF',
    'teacher.accessMaterials': 'Access Materials',
    'teacher.viewPlanner': 'View Planner',
    'teacher.newKitsAvailable': 'New STEM Kits Available',
    'teacher.trainingSession': 'Teacher Training Session',
    'teacher.searchLessons': 'Search lessons...',
    'teacher.allLevels': 'All Levels',
    'teacher.allSubjects': 'All Subjects',
    'teacher.level': 'Level',
    'teacher.subject': 'Subject',
    'teacher.difficulty': 'Difficulty',
    'teacher.learningObjectives': 'Learning Objectives',
    'teacher.assessment': 'Assessment',
    'teacher.activities': 'Activities',
    'teacher.materials': 'Materials',
    'teacher.overview': 'Overview',
    'teacher.requiredMaterials': 'Required Materials',
    'teacher.preview': 'Preview',
    'teacher.downloadMaterials': 'Download Materials',
    'teacher.noLessonsFound': 'No lessons found',
    'teacher.adjustFilters': 'Try adjusting your search or filter criteria',
    'teacher.dashboard.title': 'Dashboard',
    'teacher.minute': 'min',
    'teacher.completed': 'Completed',
    'teacher.inProgress': 'In Progress',
    'teacher.notStarted': 'Not Started',
    'teacher.complete': 'complete',
    'teacher.high': 'High',
    'teacher.medium': 'Medium',
    'teacher.low': 'Low',

  },
  ar: {
    'app.title': 'آفاق العلم',
    'app.tagline': 'آفاق المعرفة',
    'nav.home': 'الرئيسية',
    'nav.curriculum': 'المناهج',
    'nav.impact': 'التأثير',

    'nav.contact': 'اتصل بنا',
    'nav.demo': 'طلب عرض',
    'nav.login': 'دخول المعلم',
    'hero.title.revolutionizing': 'ثورة في',
    'hero.title.steam': 'تعليم ستيم',
    'hero.subtitle': 'في الأردن',
    'hero.description': 'تمكين الجيل القادم من خلال التعلم العملي لستيم مع مجموعات المناهج المبتكرة وموارد المعلمين الشاملة والدعم ثنائي اللغة السلس.',
    'steam.what.title': 'ما هو STEAM؟',
    'steam.description': 'تعليم STEAM يدمج هذه التخصصات الخمسة لخلق تجارب تعليمية عملية وجذابة تعد الطلاب لتحديات العالم الحقيقي والوظائف المستقبلية.',
    'steam.science': 'العلوم',
    'steam.technology': 'التكنولوجيا',
    'steam.engineering': 'الهندسة',
    'steam.arts': 'الفنون',
    'steam.mathematics': 'الرياضيات',
    'steam.explanation': 'العلوم والتكنولوجيا والهندسة والفنون والرياضيات',
    'hero.cta.primary': 'ابدأ رحلتك',
    'hero.cta.secondary': 'دروس نموذجية',
    'hero.stats.lessons': 'درس',
    'hero.stats.schools': 'مدرسة',
    'hero.stats.students': 'طالب',
    'curriculum.title': 'مستويات المجموعات والمناهج',
    'curriculum.subtitle': 'تعليم STEAM التدريجي المصمم وفقاً للمعايير التعليمية الأردنية، من المفاهيم الأساسية إلى مبادئ الهندسة المتقدمة. كل مستوى يتماشى مع متطلبات منهاج وزارة التربية والتعليم.',
    'curriculum.level1.title': 'المستوى 1 - المجموعة المبتدئة (الصفوف 1-3)',
    'curriculum.level1.description': 'التركيز: الإبداع، الحركة، الأشكال، بناء القصص البسيطة.',
    'curriculum.level2.title': 'المستوى 2 - مجموعة البناء (الصفوف 4-6)',
    'curriculum.level2.description': 'التركيز: الآلات البسيطة، التروس، البكرات، القوة، النسب.',
    'curriculum.level3.title': 'المستوى 3 - مجموعة المهندس (الصفوف 7-9)',
    'curriculum.level3.description': 'التركيز: الآليات الحقيقية، حل المشكلات، التحسين.',
    'curriculum.structure.title': 'هيكل المنهاج',
    'curriculum.structure.schedule': '24-30 أسبوعاً في السنة، حصة واحدة في الأسبوع',
    'curriculum.structure.cycles': '4 دورات بناء:',
    'curriculum.cycle1': 'الحركة والهيكل',
    'curriculum.cycle2': 'التروس والقوة',
    'curriculum.cycle3': 'الآليات الحقيقية',
    'curriculum.cycle4': 'الابتكار وحل المشكلات',
    'curriculum.alignment': 'كل بناء مرتبط بوحدات العلوم والرياضيات والحاسوب الأردنية',
    'curriculum.examples': 'أمثلة البناء: رافعة البكرة، سيارة صندوق التروس، روبوت راقص، ماشي كرنك',
    'footer.description': 'تمكين الجيل القادم من المبتكرين من خلال التعليم الشامل لـ STEM الذي يتماشى مع المعايير التعليمية الأردنية.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.resources': 'الموارد',
    'footer.teacherPortal': 'بوابة المعلم',
    'footer.sampleLessons': 'دروس نموذجية',
    'footer.trainingMaterials': 'مواد التدريب',
    'footer.supportCenter': 'مركز الدعم',
    'footer.copyright': '© 2025 {title}. جميع الحقوق محفوظة.',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.termsOfService': 'شروط الخدمة',
    'footer.accessibility': 'إمكانية الوصول',
    'impact.title': 'تحويل التعليم',
    'impact.subtitle': 'نتائج حقيقية من المدارس في جميع أنحاء الأردن تظهر قوة التعلم العملي لستيم.',
    'testimonials.title': 'أصوات النجاح',
    'testimonials.subtitle': 'استمع إلى المعلمين والطلاب الذين شهدوا التحول بأنفسهم.',

    'contact.title': 'ابدأ رحلتك',
    'contact.subtitle': 'هل أنت مستعد لتحويل تعليم ستيم في مدرستك؟ دعنا نناقش كيف يمكن لآفاق العلم أن تفيد طلابك.',
    'contact.form.school': 'اسم المدرسة',
    'contact.form.contact': 'الشخص المسؤول',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.levels': 'مستويات الصفوف المهتم بها',
    'contact.form.message': 'الرسالة',
    'contact.form.submit': 'إرسال الطلب',
    'dashboard.welcome': 'مرحباً بك في بوابة المعلم',
    'dashboard.curriculum': 'استعراض المناهج',
    'dashboard.resources': 'موارد التدريس',
    'dashboard.feedback': 'إرسال التقييم',
    'stats.students.reached': 'الطلاب الذين تم الوصول إليهم',
    'stats.trained.teachers': 'المعلمين المدربين',
    'stats.lessons': 'الدروس',
    'stats.schools.reached': 'المدارس التي تم الوصول إليها',
    'stats.satisfaction': 'معدل الرضا',
    'skills.problem.solving': 'مهارات حل المشكلات',
    'skills.creative.thinking': 'التفكير الإبداعي',
    'skills.collaboration': 'التعاون',
    'skills.technical': 'المهارات التقنية',
    'curriculum.grades': 'الصفوف',
    'curriculum.lessons': 'درس',
    'curriculum.viewDetails': 'عرض التفاصيل',
    'skills.outcomes.progress': 'تقدم نتائج التعلم',
    'loading': 'جاري التحميل...',
    'vision.title': 'رؤيتنا',
    'vision.content': 'إحداث ثورة في تعليم STEAM في الأردن من خلال جعل التعلم العملي متاحاً لكل طالب، وتعزيز مهارات الابتكار والإبداع والتفكير النقدي التي تعدهم لتحديات المستقبل.',
    'mission.title': 'مهمتنا',
    'mission.content': 'نحن نقدم حلول تعليمية شاملة ثنائية اللغة للعلوم والتكنولوجيا والهندسة والفنون والرياضيات من خلال مجموعات المناهج المبتكرة وتدريب المعلمين والدعم المستمر، بالشراكة مع المدارس لتحويل التعلم التقليدي إلى تجارب عملية جذابة تلهم الجيل القادم من المبتكرين وحلول المشكلات.',
    'lego.title': 'التعلم بقطع البناء',
    'lego.subtitle': 'نستخدم قطع بناء شبيهة بالليجو لجعل مفاهيم STEAM ملموسة وممتعة. يتعلم الطلاب من خلال البناء والتجريب والاكتشاف.',
    'lego.blocks.title': 'قطع البناء الملونة',
    'lego.blocks.description': 'قطع مضيئة ومترابطة تساعد الطلاب على فهم الهياكل والأنماط والمبادئ الهندسية من خلال البناء العملي.',
    'lego.mechanics.title': 'الأجزاء المتحركة والتروس',
    'lego.mechanics.description': 'عجلات وتروس وعناصر ميكانيكية تجعل الإبداعات تنبض بالحياة وتوضح مفاهيم الفيزياء عملياً.',
    'lego.smart.title': 'التكنولوجيا الذكية',
    'lego.smart.description': 'محركات وأجهزة استشعار بسيطة تعرف الطلاب على البرمجة والروبوتات بطريقة مفهومة ومتوافقة مع الليجو.',
    'lego.badge.creative': 'البناء الإبداعي',
    'lego.badge.learning': 'التعلم بالممارسة',
    'interactive.learning.title': 'التعلم بقطع البناء التفاعلية',
    'interactive.learning.subtitle': 'نستخدم قطع بناء شبيهة بالليجو لجعل المفاهيم الهندسية والعلمية ملموسة وممتعة. يتعلم الطلاب من خلال البناء والتجريب والاكتشاف.',
    'interactive.building.title': 'البناء والتصميم',
    'interactive.building.description': 'قطع البناء الملونة تساعد الطلاب على فهم الهياكل والآليات',
    'interactive.testing.title': 'التجريب والاختبار',
    'interactive.testing.description': 'يختبر الطلاب أفكارهم ويطورونها من خلال التجريب المباشر',
    'interactive.solutions.title': 'الحلول الإبداعية',
    'interactive.solutions.description': 'كل طالب يجد طريقته الخاصة لحل المشاكل والتحديات',
    'levels.title': 'مستويات المجموعات والمناهج',
    'levels.subtitle': 'تعليم STEAM التدريجي المصمم وفقاً للمعايير التعليمية الأردنية، من المفاهيم الأساسية إلى مبادئ الهندسة المتقدمة. كل مستوى يتماشى مع متطلبات منهاج وزارة التربية والتعليم.',
    
    // Teacher Portal Translations
    'teacher.dashboard': 'لوحة المعلم',
    'teacher.lessons': 'خطط الدروس',
    'teacher.announcements': 'الإعلانات',
    'teacher.resources': 'الموارد',
    'teacher.welcome': 'مرحباً',
    'teacher.logout': 'تسجيل الخروج',
    'teacher.login': 'دخول المعلمين',
    'teacher.totalLessons': 'إجمالي الدروس',
    'teacher.completedLessons': 'الدروس المكتملة',
    'teacher.activeStudents': 'الطلاب النشطون',
    'teacher.averageProgress': 'متوسط التقدم',
    'teacher.startLesson': 'بدء الدرس',
    'teacher.lessonPlan': 'الخطة',
    'teacher.teacherGuide': 'دليل المعلم',
    'teacher.lessonMaterials': 'مواد الدرس',
    'teacher.curriculumPlanner': 'مخطط المنهج',
    'teacher.downloadPDF': 'تحميل PDF',
    'teacher.accessMaterials': 'الوصول للمواد',
    'teacher.viewPlanner': 'عرض المخطط',
    'teacher.newKitsAvailable': 'مجموعات جديدة متاحة',
    'teacher.trainingSession': 'جلسة تدريب',
    'teacher.searchLessons': 'البحث عن الدروس...',
    'teacher.allLevels': 'كل المستويات',
    'teacher.allSubjects': 'كل المواضيع',
    'teacher.level': 'المستوى',
    'teacher.subject': 'الموضوع',
    'teacher.difficulty': 'الصعوبة',
    'teacher.learningObjectives': 'الأهداف التعليمية',
    'teacher.assessment': 'التقييم',
    'teacher.activities': 'الأنشطة',
    'teacher.materials': 'المواد',
    'teacher.overview': 'نظرة عامة',
    'teacher.requiredMaterials': 'المواد المطلوبة',
    'teacher.preview': 'معاينة',
    'teacher.downloadMaterials': 'تحميل المواد',
    'teacher.noLessonsFound': 'لم يتم العثور على دروس',
    'teacher.adjustFilters': 'جرب تغيير معايير البحث أو الفلتر',
    'teacher.dashboard.title': 'لوحة التحكم',
    'teacher.minute': 'دقيقة',
    'teacher.completed': 'مكتمل',
    'teacher.inProgress': 'قيد التنفيذ',
    'teacher.notStarted': 'لم يبدأ',
    'teacher.complete': 'مكتمل',
    'teacher.high': 'عاجل',
    'teacher.medium': 'متوسط',
    'teacher.low': 'منخفض',

  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'ar'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    
    // Update font family based on language
    if (language === 'ar') {
      document.body.classList.add('font-cairo');
      document.body.classList.remove('font-inter');
    } else {
      document.body.classList.add('font-inter');
      document.body.classList.remove('font-cairo');
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
